baseURL: "https://giuliao.github.io/blog/"
title: "Giuliao"
theme: PaperMod  


menu:
    main:
        - name: å½’æ¡£
          url: archives
          weight: 5
        - name: æœç´¢
          url: search/
          weight: 10
        - name: æ ‡ç­¾
          url: tags/
          weight: 10

minify:
  disableXML: true


outputs:
      home:
        - HTML
        - RSS
        - JSON # is necessary 

params:
    homeInfoParams:
        Title: HiğŸ‘‹ there, I' m Giuliao
        Content: å®‰é™æ²‰æ·€ï¼Œåšç§¯è–„å‘

    socialIcons: # optional
      - name: email
        url: "mailto: wangguang16@outlook.com"
      - name: github
        url: "https://github.com/giuliao"
    ShowReadingTime: true
    ShowCodeCopyButtons: true
    ShowPostNavLinks: true

    assets:
      favicon: "favicon.ico"

    
    ShowToc: true
    ShowBreadCrumbs: true
    fuseOpts: # search
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]